### ISSUE TITLE
大佬，我执行devtools::install_github("junjunlab/GseaVis")的时候就报错了

### ISSUE THREAD

**Issue by Zz0Co** [junjunlab/GseaVis#30]
ERROR: dependency ‘ggsankey’ is not available for package ‘GseaVis’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/GseaVis’
Warning message:
In i.p(...) :
  安装程序包‘/var/folders/1l/rg9_g1p97kd9nwh1cw3h_1j80000gn/T//RtmpBIlTpD/file6a7a1e05c1c1/GseaVis_0.1.0.tar.gz’时退出狀態的值不是0

这个是不是不支持mac的M系列芯片呀？

**Comment by junjunlab** [comment]
安装一下ggsankey包

**Comment by Zz0Co** [comment]
好的，谢谢
